<?PHP
$hostname_localhost="192.168.2.210";
if(isset($_GET["usuario"])&&isset($_GET["clave"])){

	$usuario=$_GET["usuario"];
    $clave=$_GET["clave"];
    
    $info=array("Database"=>"erpfrusys","UID"=>$usuario,"PWD"=>$clave,"CharacterSet"=>"UTF-8");
    

$conexion = sqlsrv_connect($hostname_localhost,$info);
ini_set('mssql.charset', 'UTF-8');
if($conexion){
	$json=array();
	if(isset($_GET["COD_EMP"])&&isset($_GET["COD_TEM"])&&isset($_GET["FECHA"])&&isset($_GET["FECHA2"])&&isset($_GET["DATO"])
    &&isset($_GET["PLANILLA_REC"])&&isset($_GET["CORRELATIVO"])&&isset($_GET["PLANILLA_ERP"])&&isset($_GET["IDZONA"])&&isset($_GET["SUBITEM"])){
        
        $COD_EMP=$_GET["COD_EMP"];
        $COD_TEM=$_GET["COD_TEM"];
        $FECHA=$_GET["FECHA"];
        $FECHA2=$_GET["FECHA2"];
        $DATO=$_GET["DATO"];
        $PLANILLA_REC=$_GET["PLANILLA_REC"];
        $CORRELATIVO=$_GET["CORRELATIVO"];
        $PLANILLA_ERP=$_GET["PLANILLA_ERP"];
        $IDZONA=$_GET["IDZONA"];
        $SUBITEM=$_GET["SUBITEM"];
        $sqlwhere="";

        if($IDZONA=='TODOS'){
            
        }else{
            $sqlwhere.=" AND TIT.ZON='{$IDZONA}' ";
        }
      
   
       
        

        if($DATO=='TODOS' && $FECHA=='TODOS' && $FECHA2=='TODOS' && $PLANILLA_REC=='SIN ANDROID' && $CORRELATIVO!='TODOS' && $PLANILLA_ERP!='TODOS'){
            $consulta="SELECT TIT.COD_EMP,TIT.COD_TEM,TIT.ZON,ISNULL(CONVERT(VARCHAR,ATIT.PLANILLA_REC),'SIN ANDROID') AS
            'PLANILLA_ANDROID',REC.CORRELATIVO,REC.SUBITEM,MAT.DES_SITEM,MOV.DES_MOV,REC.CAN_REC,ISNULL(REC.ID_ORDEN,0) AS
            ID_ORDEN,BOD.NOM_BOD,ISNULL(BODOR.NOM_BOD,'') AS 'BODEGA_ORIGEN',
            CONVERT(VARCHAR, TIT.FECHA_RECEPCION,23) AS 'FECHA_RECEPCION',DET.CANTIDAD AS 'CANTIDAD_ORDEN',
            TIT.PLANILLA_REC,ISNULL(CLI.NombreCliente,'')AS 'PROVEEDOR'
            FROM RECEPCIONMATERIALES REC
            INNER JOIN TIT_RECEPCIONMATERIALES TIT ON REC.COD_EMP = TIT.COD_EMP AND REC.COD_TEM= TIT.COD_TEM AND TIT.PLANILLA_REC=
            REC.PLANILLA_REC AND TIT.ZON=TIT.ZON AND TIT.SW_SERVICOS='0'
            INNER JOIN SUBITEM MAT ON MAT.COD_EMP=REC.COD_EMP AND MAT.COD_TEM=REC.COD_TEM AND REC.SUBITEM=MAT.SUBITEM
            INNER JOIN TIP_MOV MOV ON MOV.COD_EMP=TIT.COD_EMP AND MOV.COD_TEM=TIT.COD_TEM AND MOV.COD_MOV=TIT.COD_MOV AND
            MOV.COD_MOV>0 AND MOV.TIP_MOV='R'
            INNER JOIN BODEGAS BOD ON BOD.COD_EMP=TIT.COD_EMP AND BOD.COD_TEM=TIT.COD_TEM AND BOD.COD_BOD=TIT.COD_BOD
            LEFT JOIN BODEGAS BODOR ON BODOR.COD_EMP=TIT.COD_EMP AND BODOR.COD_TEM=TIT.COD_TEM AND BODOR.COD_BOD=TIT.COD_BOD_ORIGEN
            LEFT JOIN DETALLEORDEN DET ON DET.COD_EMP=REC.COD_EMP AND DET.COD_TEM=REC.COD_TEM AND DET.NRO_ORDEN=REC.ID_ORDEN AND
            REC.ZON=DET.ZON_MAT AND REC.SUBITEM=DET.SUBITEM
            LEFT JOIN PROVEEDORES CLI ON CLI.COD_EMP=TIT.COD_EMP AND CLI.COD_TEM=TIT.COD_TEM AND CLI.CodigoCliente=TIT.CODIGOCLIENTE
            LEFT JOIN ANDROID_TIT_RECEPCIONMATERIALES ATIT ON ATIT.COD_EMP=TIT.COD_EMP AND ATIT.COD_TEM=TIT.COD_TEM AND
            ATIT.ZON=TIT.ZON AND ATIT.PLANILLA_REC_ERP=TIT.PLANILLA_REC
            WHERE TIT.COD_EMP='{$COD_EMP}' AND TIT.COD_TEM='{$COD_TEM}' AND TIT.PLANILLA_REC='{$PLANILLA_ERP}' AND REC.CORRELATIVO='{$CORRELATIVO}'  AND REC.SUBITEM='{$SUBITEM}'  ".$sqlwhere;
        }

        if($DATO=='TODOS' && $FECHA=='TODOS' && $FECHA2=='TODOS' &&  $PLANILLA_REC!='SIN ANDROID' && $CORRELATIVO!='TODOS' && $PLANILLA_ERP!='TODOS' ){

            $consulta="SELECT TIT.COD_EMP,TIT.COD_TEM,TIT.ZON,ISNULL(CONVERT(VARCHAR, TIT.PLANILLA_REC),'SIN ANDROID') AS
            'PLANILLA_ANDROID',REC.CORRELATIVO,REC.SUBITEM,MAT.DES_SITEM,MOV.DES_MOV,
            REC.CAN_REC,ISNULL(REC.ID_ORDEN,0) AS ID_ORDEN,BOD.NOM_BOD AS 'BODEGA',ISNULL(BODOR.NOM_BOD ,'')AS 'BODEGA_ORIGEN',
            CONVERT(VARCHAR, TIT.FECHA_RECEPCION,23) AS 'FECHA_RECEPCION',DET.CANTIDAD AS 'CANTIDAD_ORDEN',
            TIT.PLANILLA_REC_ERP AS 'PLANILLA_REC',ISNULL(CLI.NombreCliente,'')AS 'PROVEEDOR'
            FROM ANDROID_TIT_RECEPCIONMATERIALES TIT
            INNER JOIN ANDROID_RECEPCIONMATERIALES REC ON TIT.COD_EMP=REC.COD_EMP AND TIT.COD_TEM=REC.COD_TEM AND
            TIT.PLANILLA_REC=REC.PLANILLA_REC AND TIT.ZON=REC.ZON
            INNER JOIN SUBITEM MAT ON MAT.COD_EMP=REC.COD_EMP AND MAT.COD_TEM=REC.COD_TEM AND REC.SUBITEM=MAT.SUBITEM
            INNER JOIN TIP_MOV MOV ON MOV.COD_EMP=TIT.COD_EMP AND MOV.COD_TEM=TIT.COD_TEM AND MOV.COD_MOV=TIT.COD_MOV AND
            MOV.COD_MOV>0 AND MOV.TIP_MOV='R'
            INNER JOIN BODEGAS BOD ON BOD.COD_EMP=TIT.COD_EMP AND BOD.COD_TEM=TIT.COD_TEM AND BOD.COD_BOD=TIT.COD_BOD
            LEFT JOIN BODEGAS BODOR ON BODOR.COD_EMP=TIT.COD_EMP AND BODOR.COD_TEM=TIT.COD_TEM AND BODOR.COD_BOD=TIT.COD_BOD_ORIGEN
            LEFT JOIN DETALLEORDEN DET ON DET.COD_EMP=REC.COD_EMP AND DET.COD_TEM=REC.COD_TEM AND DET.NRO_ORDEN=REC.ID_ORDEN AND
            REC.ZON=DET.ZON_MAT AND REC.SUBITEM=DET.SUBITEM
            LEFT JOIN PROVEEDORES CLI ON CLI.COD_EMP=TIT.COD_EMP AND CLI.COD_TEM=TIT.COD_TEM AND CLI.CodigoCliente=TIT.CODIGOCLIENTE
            WHERE TIT.COD_EMP='{$COD_EMP}' AND TIT.COD_TEM='{$COD_TEM}'  AND TIT.PLANILLA_REC='{$PLANILLA_REC}' AND REC.CORRELATIVO='{$CORRELATIVO}' ".$sqlwhere;


        }





        if($PLANILLA_REC=='TODOS' && $CORRELATIVO=='TODOS' && $PLANILLA_ERP=='TODOS' && $SUBITEM=='TODOS'){
            if($DATO=='FECHA' && $FECHA2==NULL){
                $sqlwhere.=" AND TIT.FECHA_RECEPCION='{$FECHA}' ";
            }
            if($DATO=='FECHA' && $FECHA2!=NULL){
                $sqlwhere.=" AND  TIT.FECHA_RECEPCION BETWEEN '{$FECHA}' AND '{$FECHA2}'";
            }
            


            if($DATO=='SUBITEM' ){
                $sqlwhere.=" AND REC.SUBITEM='{$FECHA}' ";
            }
            if($DATO=='ORDEN' ){
                $sqlwhere.=" AND REC.ID_ORDEN='{$FECHA}' ";
            }
            if($DATO =='PROVEEDOR'){
                $sqlwhere.=" AND TIT.CODIGOCLIENTE='{$FECHA}' ";
            }

            $consulta="SELECT  TIT.COD_EMP,TIT.COD_TEM,TIT.ZON,ISNULL(CONVERT(VARCHAR, TIT.PLANILLA_REC),'SIN ANDROID') AS 'PLANILLA_ANDROID',REC.CORRELATIVO,REC.SUBITEM,MAT.DES_SITEM,MOV.DES_MOV,
            REC.CAN_REC,ISNULL(REC.ID_ORDEN,0) AS ID_ORDEN,BOD.NOM_BOD AS 'BODEGA',ISNULL(BODOR.NOM_BOD ,'')AS 'BODEGA_ORIGEN',
            CONVERT(VARCHAR, TIT.FECHA_RECEPCION,23) AS 'FECHA_RECEPCION',DET.CANTIDAD AS 'CANTIDAD_ORDEN',
            TIT.PLANILLA_REC_ERP,ISNULL(CLI.NombreCliente,'')AS 'PROVEEDOR'
            FROM ANDROID_TIT_RECEPCIONMATERIALES TIT
            INNER JOIN ANDROID_RECEPCIONMATERIALES REC  ON TIT.COD_EMP=REC.COD_EMP AND TIT.COD_TEM=REC.COD_TEM AND TIT.PLANILLA_REC=REC.PLANILLA_REC AND TIT.ZON=REC.ZON
            INNER JOIN SUBITEM MAT ON MAT.COD_EMP=REC.COD_EMP AND MAT.COD_TEM=REC.COD_TEM AND REC.SUBITEM=MAT.SUBITEM
            INNER JOIN TIP_MOV MOV ON MOV.COD_EMP=TIT.COD_EMP AND MOV.COD_TEM=TIT.COD_TEM AND MOV.COD_MOV=TIT.COD_MOV AND MOV.COD_MOV>0 AND MOV.TIP_MOV='R'
            INNER JOIN BODEGAS BOD ON BOD.COD_EMP=TIT.COD_EMP AND BOD.COD_TEM=TIT.COD_TEM AND BOD.COD_BOD=TIT.COD_BOD
            LEFT JOIN BODEGAS BODOR ON BODOR.COD_EMP=TIT.COD_EMP AND BODOR.COD_TEM=TIT.COD_TEM AND BODOR.COD_BOD=TIT.COD_BOD_ORIGEN 
            LEFT JOIN DETALLEORDEN DET ON DET.COD_EMP=REC.COD_EMP AND DET.COD_TEM=REC.COD_TEM AND DET.NRO_ORDEN=REC.ID_ORDEN AND REC.ZON=DET.ZON_MAT AND REC.SUBITEM=DET.SUBITEM
            LEFT JOIN PROVEEDORES CLI ON CLI.COD_EMP=TIT.COD_EMP AND CLI.COD_TEM=TIT.COD_TEM AND CLI.CodigoCliente=TIT.CODIGOCLIENTE 
            WHERE TIT.COD_EMP='{$COD_EMP}' AND TIT.COD_TEM='{$COD_TEM}' AND TIT.PLANILLA_REC_ERP IS NULL ".$sqlwhere."UNION ALL 
          
            SELECT TIT.COD_EMP,TIT.COD_TEM,TIT.ZON,ISNULL(CONVERT(VARCHAR,ATIT.PLANILLA_REC),'SIN ANDROID') AS 'PLANILLA_ANDROID',REC.CORRELATIVO,REC.SUBITEM,MAT.DES_SITEM,MOV.DES_MOV,REC.CAN_REC,ISNULL(REC.ID_ORDEN,0) AS ID_ORDEN,BOD.NOM_BOD,ISNULL(BODOR.NOM_BOD,'') AS 'BODEGA_ORIGEN',
            CONVERT(VARCHAR, TIT.FECHA_RECEPCION,23) AS 'FECHA_RECEPCION',DET.CANTIDAD AS 'CANTIDAD_ORDEN',
            TIT.PLANILLA_REC,ISNULL(CLI.NombreCliente,'')AS 'PROVEEDOR'
            FROM  RECEPCIONMATERIALES REC
            INNER JOIN TIT_RECEPCIONMATERIALES TIT ON TIT.COD_EMP=REC.COD_EMP AND TIT.COD_TEM=REC.COD_TEM AND TIT.ZON=REC.ZON AND REC.PLANILLA_REC=TIT.PLANILLA_REC  AND TIT.SW_SERVICOS='0'
            INNER JOIN SUBITEM MAT ON MAT.COD_EMP=REC.COD_EMP AND MAT.COD_TEM=REC.COD_TEM AND REC.SUBITEM=MAT.SUBITEM
            INNER JOIN TIP_MOV MOV ON MOV.COD_EMP=TIT.COD_EMP AND MOV.COD_TEM=TIT.COD_TEM AND MOV.COD_MOV=TIT.COD_MOV AND MOV.COD_MOV>0 AND MOV.TIP_MOV='R'
            INNER JOIN BODEGAS BOD ON BOD.COD_EMP=TIT.COD_EMP AND BOD.COD_TEM=TIT.COD_TEM AND BOD.COD_BOD=TIT.COD_BOD
            LEFT JOIN BODEGAS BODOR ON BODOR.COD_EMP=TIT.COD_EMP AND BODOR.COD_TEM=TIT.COD_TEM AND BODOR.COD_BOD=TIT.COD_BOD_ORIGEN 
            LEFT JOIN DETALLEORDEN DET ON DET.COD_EMP=REC.COD_EMP AND DET.COD_TEM=REC.COD_TEM AND DET.NRO_ORDEN=REC.ID_ORDEN AND REC.ZON=DET.ZON_MAT AND REC.SUBITEM=DET.SUBITEM
            LEFT JOIN PROVEEDORES CLI ON CLI.COD_EMP=TIT.COD_EMP AND CLI.COD_TEM=TIT.COD_TEM AND CLI.CodigoCliente=TIT.CODIGOCLIENTE 
            LEFT JOIN ANDROID_TIT_RECEPCIONMATERIALES ATIT ON ATIT.COD_EMP=TIT.COD_EMP AND ATIT.COD_TEM=TIT.COD_TEM AND ATIT.ZON=TIT.ZON AND ATIT.PLANILLA_REC_ERP=TIT.PLANILLA_REC and ATIT.CODIGOCLIENTE=TIT.CODIGOCLIENTE
            WHERE TIT.COD_EMP='{$COD_EMP}' AND TIT.COD_TEM='{$COD_TEM}' ".$sqlwhere."ORDER BY FECHA_RECEPCION DESC, DES_SITEM ASC";

        }

    
       
		$resultado=sqlsrv_query($conexion,$consulta);
		
		while($registro =sqlsrv_fetch_array($resultado)){
			$json[]=$registro;
		}

		
		echo json_encode($json);
		

	}else{
		$resultar["message"]='Ws no Retorna';
		$json[]=$resultar;
		echo json_encode($json);
	}

}else{
	echo "CONEXION FALLIDA";
}
}else{
	$resultar["message"]='Sin usuario';
		$json[]=$resultar;
		echo json_encode($json);
} 	
?>