<?PHP
$hostname_localhost="192.168.2.210";
if(isset($_GET["usuario"])&&isset($_GET["clave"])){

	$usuario=$_GET["usuario"];
    $clave=$_GET["clave"];
    
    $info=array("Database"=>"erpfrusys","UID"=>$usuario,"PWD"=>$clave,"CharacterSet"=>"UTF-8");
    

$conexion = sqlsrv_connect($hostname_localhost,$info);
ini_set('mssql.charset', 'UTF-8');
if($conexion){
	$json=array();
	if(isset($_GET["COD_EMP"])&&isset($_GET["COD_TEM"])&&isset($_GET["ZON"])){
        
        $COD_EMP=$_GET["COD_EMP"];
        $COD_TEM=$_GET["COD_TEM"];
        $ZON=$_GET["ZON"];
		
		$consulta="SELECT DETALLEORDEN.ZON_MAT,  ZONAS.NOM_ZON,  ORDEN.NRO_ORDEN,  ORDEN.CODIGOCLIENTE, PROVEEDORES.NombreCliente,CONVERT(VARCHAR, ORDEN.FEC_ORDEN,111) AS 'FEC_ORDEN',  
        ORDEN.ZON,  ZONAS_1.NOM_ZON AS ZON_PROC ,DETALLEORDEN.SUBITEM,SUBITEM.DES_SITEM,DETALLEORDEN.CANTIDAD,ORDEN.OBS_ORDEN
        FROM ORDEN 
        INNER JOIN DETALLEORDEN ON ORDEN.COD_EMP = DETALLEORDEN.COD_EMP AND  ORDEN.ZON = DETALLEORDEN.ZON AND ORDEN.NRO_ORDEN = DETALLEORDEN.NRO_ORDEN AND  ORDEN.COD_TEM = DETALLEORDEN.COD_TEM AND DETALLEORDEN.ZON_MAT='{$ZON}' 
        INNER JOIN ZONAS ON DETALLEORDEN.COD_EMP = ZONAS.COD_EMP AND  DETALLEORDEN.COD_TEM = ZONAS.COD_TEM AND DETALLEORDEN.ZON_MAT = ZONAS.ZON 
        INNER JOIN ZONAS ZONAS_1 ON ORDEN.COD_EMP = ZONAS_1.COD_EMP AND  ORDEN.COD_TEM = ZONAS_1.COD_TEM AND ORDEN.ZON = ZONAS_1.ZON
        INNER JOIN SUBITEM ON SUBITEM.SUBITEM=DETALLEORDEN.SUBITEM AND SUBITEM.COD_EMP=DETALLEORDEN.COD_EMP AND SUBITEM.COD_TEM=DETALLEORDEN.COD_TEM
        INNER JOIN PROVEEDORES ON PROVEEDORES.COD_EMP=ORDEN.COD_EMP AND PROVEEDORES.COD_TEM=ORDEN.COD_TEM AND PROVEEDORES.CodigoCliente=ORDEN.CODIGOCLIENTE
        WHERE ORDEN.COD_EMP='{$COD_EMP}' AND ORDEN.COD_TEM='{$COD_TEM}'   AND ORDEN.STATUS <> 0 AND ORDEN.ESTADO='A' AND 
        EXISTS(SELECT 1 FROM APROBACION_ORDEN_GE_ADM AP WHERE AP.COD_EMP=DETALLEORDEN.COD_EMP AND AP.COD_TEM=DETALLEORDEN.COD_TEM AND  AP.ZON_MAT=DETALLEORDEN.ZON_MAT AND AP.NRO_ORDEN=DETALLEORDEN.NRO_ORDEN AND AP.ADMINISTRADOR=1 AND AP.GERENCIA=1) AND 
        DETALLEORDEN.ZON_MAT = '{$ZON}' 
        GROUP BY ORDEN.NRO_ORDEN, ORDEN.CODIGOCLIENTE, ORDEN.FEC_ORDEN, DETALLEORDEN.ZON_MAT, ZONAS.NOM_ZON , 
        ORDEN.ZON, ZONAS_1.NOM_ZON,DETALLEORDEN.SUBITEM,SUBITEM.DES_SITEM,DETALLEORDEN.CANTIDAD,ORDEN.OBS_ORDEN,PROVEEDORES.NombreCliente";
		
		$resultado=sqlsrv_query($conexion,$consulta);
		
		while($registro =sqlsrv_fetch_array($resultado)){
			$json[]=$registro;
		}

		
		echo json_encode($json);
		

	}else{
		$resultar["message"]='Ws no Retorna';
		$json[]=$resultar;
		echo json_encode($json);
	}

}else{
	echo "CONEXION FALLIDA";
}
}else{
	$resultar["message"]='Sin usuario';
		$json[]=$resultar;
		echo json_encode($json);
} 	
?>